using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EMA.Migrations
{
    /// <inheritdoc />
    public partial class EnforceGenderCheck : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Ensure there are no invalid or NULL values before adding the CHECK constraint
            migrationBuilder.Sql("UPDATE [Employees] SET [Gender] = N'M' WHERE [Gender] IS NULL OR [Gender] NOT IN (N'M', N'F');");

            // Drop the default constraint for Gender if it exists (name may be autogenerated)
            migrationBuilder.Sql(@"DECLARE @dfName sysname;
SELECT @dfName = dc.name
FROM sys.default_constraints dc
JOIN sys.columns c ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
JOIN sys.tables t ON t.object_id = c.object_id
WHERE t.name = 'Employees' AND c.name = 'Gender';
IF @dfName IS NOT NULL
    EXEC('ALTER TABLE [Employees] DROP CONSTRAINT [' + @dfName + ']');");

            // Ensure column definition (removes DB default via AlterColumn if necessary)
            migrationBuilder.AlterColumn<string>(
                name: "Gender",
                table: "Employees",
                type: "nvarchar(1)",
                maxLength: 1,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(1)",
                oldMaxLength: 1,
                oldDefaultValue: "M");

            // Add CHECK constraint to enforce allowed values (M/F)
            migrationBuilder.Sql(@"IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE name = 'CK_Employees_Gender')
BEGIN
    ALTER TABLE [Employees] ADD CONSTRAINT CK_Employees_Gender CHECK ([Gender] IN (N'M', N'F'));
END");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove CHECK constraint if present
            migrationBuilder.Sql(@"IF EXISTS (SELECT * FROM sys.check_constraints WHERE name = 'CK_Employees_Gender')
BEGIN
    ALTER TABLE [Employees] DROP CONSTRAINT CK_Employees_Gender;
END");

            // Restore DB default for Gender to 'M'
            migrationBuilder.AlterColumn<string>(
                name: "Gender",
                table: "Employees",
                type: "nvarchar(1)",
                maxLength: 1,
                nullable: false,
                defaultValue: "M",
                oldClrType: typeof(string),
                oldType: "nvarchar(1)",
                oldMaxLength: 1);
        }
    }
}
